name: interval_watch
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  wakelock_plus: ^1.2.0
  google_fonts: ^6.1.0
  intl: ^0.19.0
  cupertino_icons: ^1.0.2
  flutter_tts: ^4.2.3
  shared_preferences: ^2.5.3
  table_calendar: ^3.1.3

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1

  # Share features
  share_plus: ^10.0.0
  path_provider: ^2.1.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.2
  build_runner: ^2.4.6

flutter:
  generate: true
  uses-material-design: true
